### ISSUE TITLE
增加对过往学期的课程的支持

### ISSUE THREAD

**Issue by JiayanJohnnyChu** [TMYTiMidlY/capture-courses#1]
部分课程并非每学期都开设，如果能增加对过往学期的课程的支持（如：https://v.ustc.edu.cn/0/2022-2/capture-course/PHYS5002P.01/detail）将会方便很多，感谢开发者

**Comment by TMYTiMidlY** [comment]
已经添加了对往期课程的支持，可惜你提到的课程视频平台上仅有一节录课。我本来也想在下学期修读或旁听广相的课，没想到居然不开了T_T
