### ISSUE TITLE
研究生课均显示“当前还没有课程内容”

### ISSUE THREAD

**Issue by k-telux** [TMYTiMidlY/capture-courses#5]
是因为研究生院没有默认进行录课？

**Comment by k-telux** [comment]
![012515551D50BAC531E4B10AF4B8B9C0](https://github.com/TMYTiMidlY/capture-courses/assets/87649762/c559b2d2-df37-4557-8200-d56526fadd4f)

**Comment by TMYTiMidlY** [comment]
用录课平台的后端api查询，"量子光学" [v.ustc.edu.cn/api/v1/course/8706/schedules](https://v.ustc.edu.cn/api/v1/course/8706/schedules) 返回空数据，而本科生课"量子力学A" [v.ustc.edu.cn/api/v1/course/7234/schedules](https://v.ustc.edu.cn/api/v1/course/7234/schedules) 是有录课信息的，所以这不是前端能解决的问题
