### ISSUE TITLE
20级的瀚海账号貌似看不了

### ISSUE THREAD

**Issue by zbz02** [TMYTiMidlY/capture-courses#6]
和另一个20级的同学试了试，我们登录瀚海后都显示课程未公开

**Comment by TMYTiMidlY** [comment]
请在登录账号后在新标签页访问[这个链接](https://v.ustc.edu.cn/api/v1/captures/f675a3d52f254bd49eae338dcf4803bc/capture-iframe-url)，并检查"url"字段内的链接能否正常访问。
