### ISSUE TITLE
新的限制

### ISSUE THREAD

**Issue by MCerKirby** [TMYTiMidlY/capture-courses#7]
在近日（大概是三五天以内）这个办法突然不能用了，在相同的操作下会跳转进入https://v.ustc.edu.cn/no-permission/COURSE_IS_PRIVATE?fromPath=（先前的v.ustc.edu.cn/之后的部分链接）。在多次刷新卡网速的尝试下发现有小几率（目前只有一次）卡到课程录像页面，但具体按钮不可使用（会再次跳转）。在最后一个issue您写出的那个链接可以使用。

**Comment by TMYTiMidlY** [comment]
8月19日左右网站做了更新，请重新下载最新版的代码。只要 #6 中提到的链接可以使用，就说明网站没有做服务端校验，我们这种客户端的破解基本上没问题。

**Comment by MCerKirby** [comment]
我使用的就是新版本的代码，重复下载了三次都会遇到这个问题qwq

**Comment by MCerKirby** [comment]
是不是我在操作上出了差错？我按F12-清除配置-选择替代文件夹-点击允许访问权限的顺序，并且保持侧边栏的开启，仍然会出现页面跳转的情形

**Comment by TMYTiMidlY** [comment]
可能是页面没有刷新，覆写没有生效，这一点我在新版的README中加上了。你看看替代选项卡那里的文件右下角有没有出现紫色点？就像<https://learn.microsoft.com/zh-cn/microsoft-edge/devtools-guide-chromium/javascript/overrides#adding-files-to-your-overrides-folder>中提到的一样

**Comment by MCerKirby** [comment]
刷新过若干次，名为captureCourses-571fa455的文件右下角有紫色圆点，但名为capture-443b2e25的文件没有
![pic](https://github.com/user-attachments/assets/d6ea56fb-b167-4ef7-af98-be7d77775594)

**Comment by TMYTiMidlY** [comment]
在进入具体的视频之前，这种情况是正常的，capture-443b2e25.js的覆写是为了让下图的这个请求的响应为图中所示，而不是响应error，你可以搜索”相对论 23春“，在点”观看回放“之前，先清空开发者工具”网络“的记录，然后点击观看回放，找到这条网络请求，看看是否如图中所示。
![image](https://github.com/user-attachments/assets/1547bf69-baa1-4c20-b4f2-b365576d0dab)

**Comment by MCerKirby** [comment]
收到，谢谢您。刚才经过对照发现，在进入录课页面之前要先打开开发者工具再进入链接，才能正常看课；若先进入界面再打开开发者工具，则会直接跳转无权限界面。

**Comment by TMYTiMidlY** [comment]
不客气，我也更新一下README的描述。
