### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by Azrael135** [TMYTiMidlY/capture-courses#8]
您好，开发者，您这个脚本我使用了一下，无法打开课号019XXX的课程回放，操作都没有问题，完全按照readme.md指导

**Comment by TMYTiMidlY** [comment]
我试了一下查看 019161.07 的课程回放，没有发现什么问题。如果点进课程后发现如下图所示，可能是学校并没有安排这门课程的录像。
![image](https://github.com/user-attachments/assets/d726cc30-9cbf-48a9-b9f7-0096ddf74116)

**Comment by Azrael135** [comment]
好的，谢谢，我会再尝试一下！







-----Original Messages-----
From:TMYTiMidlY ***@***.***>
Send time:Tuesday, 09/17/2024 15:10:19
To: TMYTiMidlY/capture-courses ***@***.***>
Cc: Azrael135 ***@***.***>, Author ***@***.***>
Subject: Re: [TMYTiMidlY/capture-courses] 无法使用 (Issue #8)






我试了一下查看 019161.07 的课程回放，没有发现什么问题。如果点进课程后发现如下图所示，可能是学校并没有安排这门课程的录像。
image.png (view on web)

**Comment by Azrael135** [comment]
What is issue #8 ？I cannot find this


发件人：TMYTiMidlY ***@***.***>
发送日期：2024-10-08 16:20:04
收件人：TMYTiMidlY/capture-courses ***@***.***>
抄送人：Azrael135 ***@***.***>, Author ***@***.***>
主 题：Re: [TMYTiMidlY/capture-courses] 无法使用 (Issue #8)


Closed #8 as completed.
